// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawmaxwL_LKKO0hv_-lpewiBtT9-58r28',
    appId: '1:140879515966:web:4fc8b8355ab8a64e66dc6f',
    messagingSenderId: '140879515966',
    projectId: 'sample-app-distribution-7e887',
    authDomain: 'sample-app-distribution-7e887.firebaseapp.com',
    storageBucket: 'sample-app-distribution-7e887.firebasestorage.app',
    measurementId: 'G-1NSYW7X71B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdkruavV8n8a_6nWFissNHaqwM4wOVbTg',
    appId: '1:140879515966:android:6795992c63e5aa8066dc6f',
    messagingSenderId: '140879515966',
    projectId: 'sample-app-distribution-7e887',
    storageBucket: 'sample-app-distribution-7e887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwAaf_SlPRxYmfoGYtVFRFk4HGK7GQ2Ko',
    appId: '1:140879515966:ios:a7e5bc257c0b866066dc6f',
    messagingSenderId: '140879515966',
    projectId: 'sample-app-distribution-7e887',
    storageBucket: 'sample-app-distribution-7e887.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwAaf_SlPRxYmfoGYtVFRFk4HGK7GQ2Ko',
    appId: '1:140879515966:ios:a7e5bc257c0b866066dc6f',
    messagingSenderId: '140879515966',
    projectId: 'sample-app-distribution-7e887',
    storageBucket: 'sample-app-distribution-7e887.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDawmaxwL_LKKO0hv_-lpewiBtT9-58r28',
    appId: '1:140879515966:web:1dd0d87b276faeef66dc6f',
    messagingSenderId: '140879515966',
    projectId: 'sample-app-distribution-7e887',
    authDomain: 'sample-app-distribution-7e887.firebaseapp.com',
    storageBucket: 'sample-app-distribution-7e887.firebasestorage.app',
    measurementId: 'G-YJ2ZJQNQQJ',
  );
}
